name: Run Checks

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          architecture: "x64"
      - run: pip install -r requirements.txt
      - run: codespell
      - run: black --check .
      - run: isort --check --diff .
      - run: pylint pybotvac
      - run: flake8 pybotvac
      - run: bandit -r pybotvac
